query {
	repositoryOwner(login: "silvandiepen") {
		repository(name: "silvandiepen-snippets") {
			object(expression: "master:") {
				... on Tree {
					entries {
						name
						object {
							... on Blob {
								text
							}
						}
					}
				}
			}
		}
	}
}
